type: qdrant
collection_name: northwind
path: ./data/stores/northwind_store
#url: ${QDRANT_URL}
#api_key: ${QDRANT_API_KEY}
batch_size: 
sync_on_startup: false
embedding:
  type: openai
  model_name: text-embedding-3-small 
  api_key: ${OPENAI_API_KEY}