# config.yaml
database:
  type: postgres  # o mysql o snowflake
  host: localhost
  port: 5432
  database: postgres
  user: postgres
  password: ${POSTGRES_PWD}  # Prende il valore dalla variabile d'ambiente
  schema: &db_schema video_games
  # Configurazioni opzionali per Snowflake
  # warehouse: compute_wh
  # account: xy12345.eu-central-1
  # role: analyst

llm:
  type: ollama    # openai, ollama
  # Configurazioni per ollama
  base_url: http://localhost:11434
  model: llama3.1
  language: english # sql query explanation language
  # Configurazioni per OpenAI
  #api_key: ${OPENAI_API_KEY}

prompt:
  include_sample_data: true
  max_sample_rows: 3

vector_store:
  enabled: false
  type: qdrant
  collection_name: ${db_schema}_store
  path: ./data/${db_schema}_store
  #url: http://localhost:6333
  # api_key: optional
  batch_size: 100
  embedding:
    type: huggingface # type: openai, huggingface
    model_name: sentence-transformers/multi-qa-MiniLM-L6-cos-v1  # sentence-transformers/multi-qa-MiniLM-L6-cos-v1 , text-embedding-3-small text-embedding-3-large
    #api_key: ${OPENAI_API_KEY} # Per OpenAI

debug: true