# northwind_postgres.yaml
database:
  type: postgres  # o mysql o snowflake
  host: localhost
  port: 5432
  database: giacomo
  user: postgres
  password: ${POSTGRES_PWD}
  schema: &db_schema northwind
  # Configurazioni opzionali per Snowflake
  # warehouse: compute_wh
  # account: xy12345.eu-central-1
  # role: analyst

cache:
  enabled: true
  directory: ./data/cache/${db_schema}
  ttl_hours: 336

llm:
  type: openai    # openai, ollama
  # Configurazioni per ollama
  #base_url: http://localhost:11434
  model: gpt-4o
  language: english # sql query explanation language
  # Configurazioni per OpenAI
  api_key: ${OPENAI_API_KEY}

prompt:
  include_sample_data: true
  max_sample_rows: 2

vector_store:
  enabled: true
  type: qdrant
  collection_name: ${db_schema}
  #path: ./data/${db_schema}_store
  url: ${QDRANT_URL}
  api_key: ${QDRANT_API_KEY}
  batch_size: 100
  embedding:
    type: openai # type: openai, huggingface
    model_name: text-embedding-3-small  # sentence-transformers/multi-qa-MiniLM-L6-cos-v1 , text-embedding-3-small text-embedding-3-large
    api_key: ${OPENAI_API_KEY} # Per OpenAI

debug: true